stages:
- buildnumber
- docker

trigger:buildnumber:backend:
  tags:
  - Shell
  stage: buildnumber
  when: on_success
  only:
  - /^rel-.+_FEATURE$/
  except:
  - tags
  - triggers
  script:
  - set -x
  - BUILDNUMBER=$(cat RELEASE | grep BUILDNUMBER | cut -d' ' -f3 | cut -d'-' -f1)
  - BUILDNUMBER=$((BUILDNUMBER+1))
  - sed -i -e "s/^BUILDNUMBER = .*$/BUILDNUMBER = $BUILDNUMBER/g" RELEASE
  - cat RELEASE

trigger:docker:backend:
  tags:
  - Curl
  stage: docker
  when: on_success
  only:
  - /^rel-.+_FEATURE$/
  except:
  - tags
  - triggers
  script:
  - curl -x http://proxy.intra.cape-it.de:3128 http://docker.vm.devel.cape-it.de/cgi-bin/update_image_kix18-backend
