stages:
- buildnumber
- docker

trigger:buildnumber:backend:
  tags:
  - Shell
  stage: buildnumber
  when: on_success
  only:
  - /^rel-.+_FEATURE$/
  except:
  - tags
  - triggers
  script:
  - BUILDNUMBER=$(cat RELEASE | grep BUILDNUMBER | cut -d' ' -f3 | cut -d'-' -f1)
  - BUILDNUMBER=$((BUILDNUMBER+1))
  - sed -i -e "s/^BUILDNUMBER = .*$/BUILDNUMBER = $BUILDNUMBER/g" RELEASE
  - git config --global user.name "Gitlab Runner"
  - git config --global user.email gitlab-runner@git.intra.cape-it.de
  - git config --global push.default simple
  - git add RELEASE
  - git commit -a -m "[skip ci] increased build number"
  - git push

trigger:docker:backend:
  tags:
  - Curl
  stage: docker
  when: on_success
  only:
  - /^rel-.+_FEATURE$/
  except:
  - tags
  - triggers
  script:
  - curl -x http://proxy.intra.cape-it.de:3128 http://docker.vm.devel.cape-it.de/cgi-bin/update_image_kix18-backend
