variables:
  GIT_STRATEGY: clone
  
stages:
- update
- build
- sync
- update docker image

increase build number:
  tags:
    - Shell
  stage: update
  when: on_success
  only:
    - /^rel-.+_FEATURE$/
  except:
    - tags
    - triggers
  script:
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email GITLAB_USER_EMAIL
    - git config --global push.default simple
    - git checkout $CI_COMMIT_REF_NAME
    - BUILDNUMBER=$(cat RELEASE | grep BUILDNUMBER | cut -d' ' -f3 | cut -d'-' -f1)
    - BUILDNUMBER=$((BUILDNUMBER+1))
    - BUILDDATE=$(date --rfc-2822)
    - BUILDHOST=$(hostname -f)
    - sed -i -e "s/^BUILDNUMBER = .*$/BUILDNUMBER = $BUILDNUMBER/g" RELEASE
    - sed -i -e "s/^BUILDDATE = .*$/BUILDDATE = $BUILDDATE/g" RELEASE
    - sed -i -e "s/^BUILDHOST = .*$/BUILDHOST = $BUILDHOST/g" RELEASE
    - git add RELEASE
    - git commit -a -m "[skip ci] increased build number"
    - git tag build-$BUILDNUMBER
    - git pull
    - git push http://gitlab-ci:_Ts7VRzvsKRbhguJjByv@git.intra.cape-it.de/$CI_PROJECT_PATH

build backend:
  tags:
    - Shell
  stage: build
  except:
    - tags
    - schedules
    - triggers 
  script:   
    - tar cvfz kix-backend.tar.gz * --exclude=kix-backend.tar.gz
    - md5sum -b kix-backend.tar.gz
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email GITLAB_USER_EMAIL
    - git config --global push.default simple
    - git checkout $CI_COMMIT_REF_NAME
    - git tag -f build-$CI_COMMIT_REF_NAME
    - git push -f --tags http://gitlab-ci:_Ts7VRzvsKRbhguJjByv@git.intra.cape-it.de/$CI_PROJECT_PATH
    - curl -u gitlab-ci:Ait4ugh2 -T kix-backend.tar.gz "http://artifactory.kix18.docker.vm.devel.cape-it.de/artifactory/kix18/backend/build-$CI_COMMIT_REF_NAME/kix-backend.tar.gz?gitlab-project=$CI_PROJECT_URL;gitlab-job=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID"  
  artifacts:
    paths:
      - kix-backend.tar.gz
    expire_in: 1 week
  allow_failure: false

update docker image:
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://docker.vm.devel.cape-it.de:3001/
  tags:
    - Curl
  stage: build
  when: on_success
  only:
    - /^rel-.+_FEATURE$/
  except:
    - schedules
    - tags
    - triggers
  script:
    - curl -x http://proxy.intra.cape-it.de:3128 http://docker.vm.devel.cape-it.de/cgi-bin/update_kix18_test-simple

github sync:
  only:
    - rel-18
  except:
    - schedules
    - tags
    - triggers
  stage: sync
  allow_failure: true
  script:
    - git checkout origin/rel-18
    - git filter-branch --force --index-filter "git rm --cached --ignore-unmatch .gitlab-ci.yml" --prune-empty --tag-name-filter cat -- --all
    - git remote add github https://capeit-githubrobot:(KIX5tart4A11)!@github.com/cape-it/kix-backend.git
    - git push --force github HEAD:master
    - git remote remove github