stages:
- buildnumber
- docker

trigger:buildnumber:backend:
  tags:
  - Shell
  stage: buildnumber
  when: on_success
  only:
  - /^rel-.+_FEATURE$/
  except:
  - tags
  - triggers
  script:
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global user.email GITLAB_USER_EMAIL
  - git config --global push.default simple
  - git checkout $CI_COMMIT_REF_NAME
  - BUILDNUMBER=$(cat RELEASE | grep BUILDNUMBER | cut -d' ' -f3 | cut -d'-' -f1)
  - BUILDNUMBER=$((BUILDNUMBER+1))
  - sed -i -e "s/^BUILDNUMBER = .*$/BUILDNUMBER = $BUILDNUMBER/g" RELEASE
  - git add RELEASE
  - git commit -a -m "[skip ci] increased build number"
  - git tag build-$BUILDNUMBER
  - git push http://$CI_USER_LOGIN:_Ts7VRzvsKRbhguJjByv@git.intra.cape-it.de/$CI_PROJECT_NAMESPACE/$CI_PROJECT_PATH build-$BUILDNUMBER

trigger:docker:backend:
  tags:
  - Curl
  stage: docker
  when: on_success
  only:
  - /^rel-.+_FEATURE$/
  except:
  - tags
  - triggers
  script:
  - curl -x http://proxy.intra.cape-it.de:3128 http://docker.vm.devel.cape-it.de/cgi-bin/update_image_kix18-backend
